# Get the base image
FROM centos

LABEL Remarks="This is a dockerfile for centos"
RUN yum -y install openssh-server openssh-clients 
RUN /usr/bin/ssh-keygen -A 
#CMD /usr/sbin/sshd -D >/dev/null &
CMD /usr/sbin/sshd -D
RUN ssh-keygen   -t rsa -f /root/.ssh/id_rsa -q  -N ""
RUN cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys
RUN rm /run/nologin
